/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DllWrapper */

#ifndef _Included_DllWrapper
#define _Included_DllWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DllWrapper
 * Method:    getFreeSpace
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_DllWrapper_getFreeSpace
  (JNIEnv *, jobject, jstring);

/*
 * Class:     DllWrapper
 * Method:    setWakeUpTime
 * Signature: (IIIIII)I
 */
JNIEXPORT jint JNICALL Java_DllWrapper_setWakeUpTime
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     DllWrapper
 * Method:    setNextScheduleTime
 * Signature: (IIIIII)I
 */
JNIEXPORT jint JNICALL Java_DllWrapper_setNextScheduleTime
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     DllWrapper
 * Method:    setActiveCount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_DllWrapper_setActiveCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     DllWrapper
 * Method:    setCurrentPort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_DllWrapper_setCurrentPort
  (JNIEnv *, jobject, jint);

/*
 * Class:     DllWrapper
 * Method:    setKbLEDs
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_DllWrapper_setKbLEDs
  (JNIEnv *, jobject, jint);

/*
 * Class:     DllWrapper
 * Method:    setEvent
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_DllWrapper_setEvent
  (JNIEnv *, jobject, jstring);

/*
 * Class:     DllWrapper
 * Method:    setNotification
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_DllWrapper_setNotification
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
