#define _STR(x) #x
#define STR(x) _STR(x)

#define VERSION_MAJOR 1
#define VERSION_MINOR 0
#define VERSION_BUILD 295
#define VERSION_QFE 0
#define VERSION_LASTBUILD_DATE "2023/04/07 11:14:55"
#define VERSION_BUILD_DATE "2023/04/17 18:56:37"

#define VERSION_NUMBER VERSION_MAJOR,VERSION_MINOR,VERSION_BUILD,VERSION_QFE
#define VERSION_STRING STR(VERSION_MAJOR) "." STR(VERSION_MINOR) "." STR(VERSION_BUILD) "." STR(VERSION_QFE)
#define VERSION_COMPANY "Blue Bit Solutions - JC Build"
#define VERSION_COPYRIGHT "Copyright (C) 2009-2023"
#define VERSION_TRADEMARK ""
#define VERSION_DESC "TVSchedulerPro-JC"

